replicaCount: 1

image:
  repository: itzg/minecraft-server
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 25565

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
