apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-config
data:
  server.properties: |
    enable-command-block=true
    spawn-monsters=true
    max-players=10
    ops.json: |
    [
      {
        "name": "Helinton",
        "level": 4,
        "bypassesPlayerLimit": false
      }
    ]
